// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RedLab.API.Data;

#nullable disable

namespace RedLab.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260602033513_SeedProductosDePrueba")]
    partial class SeedProductosDePrueba
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RedLab.API.Entities.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"),
                            Descripcion = "Laptop de alta gama para desarrollo de software",
                            Estado = true,
                            FechaCreacion = new DateTime(2026, 6, 2, 3, 35, 12, 858, DateTimeKind.Utc).AddTicks(3102),
                            FechaModificacion = new DateTime(2026, 6, 2, 3, 35, 12, 858, DateTimeKind.Utc).AddTicks(3103),
                            Nombre = "Laptop Pro 15 pulgadas",
                            Precio = 1299.99m,
                            UsuarioCreacion = "SystemAdmin",
                            UsuarioModificacion = "SystemAdmin"
                        },
                        new
                        {
                            Id = new Guid("f4e3d2c1-b0a9-8f7e-6d5c-4b3a2a1f0e9d"),
                            Descripcion = "Monitor curvo ideal para multitasking",
                            Estado = true,
                            FechaCreacion = new DateTime(2026, 6, 2, 3, 35, 12, 858, DateTimeKind.Utc).AddTicks(3110),
                            FechaModificacion = new DateTime(2026, 6, 2, 3, 35, 12, 858, DateTimeKind.Utc).AddTicks(3111),
                            Nombre = "Monitor UltraWide 34\"",
                            Precio = 450.50m,
                            UsuarioCreacion = "SystemAdmin",
                            UsuarioModificacion = "SystemAdmin"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7e"),
                            Descripcion = "Teclado con switches mecánicos silenciosos y distribución ISO",
                            Estado = true,
                            FechaCreacion = new DateTime(2026, 6, 2, 3, 35, 12, 858, DateTimeKind.Utc).AddTicks(3115),
                            FechaModificacion = new DateTime(2026, 6, 2, 3, 35, 12, 858, DateTimeKind.Utc).AddTicks(3115),
                            Nombre = "Teclado Mecánico RGB",
                            Precio = 89.99m,
                            UsuarioCreacion = "SystemAdmin",
                            UsuarioModificacion = "SystemAdmin"
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-9c0d-1e2f-3a4b5c6d7e8f"),
                            Descripcion = "Mouse con sensor de alta precisión y batería recargable de larga duración",
                            Estado = true,
                            FechaCreacion = new DateTime(2026, 6, 2, 3, 35, 12, 858, DateTimeKind.Utc).AddTicks(3119),
                            FechaModificacion = new DateTime(2026, 6, 2, 3, 35, 12, 858, DateTimeKind.Utc).AddTicks(3120),
                            Nombre = "Mouse Ergonómico Inalámbrico",
                            Precio = 59.90m,
                            UsuarioCreacion = "SystemAdmin",
                            UsuarioModificacion = "SystemAdmin"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-0d1e-2f3a-4b5c6d7e8f9a"),
                            Descripcion = "32GB RAM, 1TB SSD NVMe, procesador de última generación para desarrollo",
                            Estado = true,
                            FechaCreacion = new DateTime(2026, 6, 2, 3, 35, 12, 858, DateTimeKind.Utc).AddTicks(3125),
                            FechaModificacion = new DateTime(2026, 6, 2, 3, 35, 12, 858, DateTimeKind.Utc).AddTicks(3125),
                            Nombre = "Laptop Pro 16\"",
                            Precio = 1350.00m,
                            UsuarioCreacion = "SystemAdmin",
                            UsuarioModificacion = "SystemAdmin"
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-c9d0-1e2f-3a4b-5c6d7e8f9a0b"),
                            Descripcion = "Adaptador de aluminio con puertos HDMI 4K, SD, MicroSD y USB 3.0",
                            Estado = true,
                            FechaCreacion = new DateTime(2026, 6, 2, 3, 35, 12, 858, DateTimeKind.Utc).AddTicks(3128),
                            FechaModificacion = new DateTime(2026, 6, 2, 3, 35, 12, 858, DateTimeKind.Utc).AddTicks(3129),
                            Nombre = "Hub USB-C 8 en 1",
                            Precio = 42.50m,
                            UsuarioCreacion = "SystemAdmin",
                            UsuarioModificacion = "SystemAdmin"
                        },
                        new
                        {
                            Id = new Guid("f6a7b8c9-d0e1-2f3a-4b5c-6d7e8f9a0b1c"),
                            Descripcion = "Silla con soporte lumbar ajustable y reposabrazos 3D",
                            Estado = true,
                            FechaCreacion = new DateTime(2026, 6, 2, 3, 35, 12, 858, DateTimeKind.Utc).AddTicks(3133),
                            FechaModificacion = new DateTime(2026, 6, 2, 3, 35, 12, 858, DateTimeKind.Utc).AddTicks(3133),
                            Nombre = "Silla Ergonómica de Oficina",
                            Precio = 210.00m,
                            UsuarioCreacion = "SystemAdmin",
                            UsuarioModificacion = "SystemAdmin"
                        },
                        new
                        {
                            Id = new Guid("0a1b2c3d-4e5f-6a7b-8c9d-0e1f2a3b4c5d"),
                            Descripcion = "Almacenamiento portátil USB 3.2 de alta velocidad con cifrado de hardware",
                            Estado = true,
                            FechaCreacion = new DateTime(2026, 6, 2, 3, 35, 12, 858, DateTimeKind.Utc).AddTicks(3154),
                            FechaModificacion = new DateTime(2026, 6, 2, 3, 35, 12, 858, DateTimeKind.Utc).AddTicks(3154),
                            Nombre = "Disco Duro Externo 2TB",
                            Precio = 75.00m,
                            UsuarioCreacion = "SystemAdmin",
                            UsuarioModificacion = "SystemAdmin"
                        },
                        new
                        {
                            Id = new Guid("1b2c3d4e-5f6a-7b8c-9d0e-1f2a3b4c5d6e"),
                            Descripcion = "Auriculares circumaurales inalámbricos con ANC activo ideal para llamadas",
                            Estado = true,
                            FechaCreacion = new DateTime(2026, 6, 2, 3, 35, 12, 858, DateTimeKind.Utc).AddTicks(3157),
                            FechaModificacion = new DateTime(2026, 6, 2, 3, 35, 12, 858, DateTimeKind.Utc).AddTicks(3158),
                            Nombre = "Auriculares con Cancelación de Ruido",
                            Precio = 180.00m,
                            UsuarioCreacion = "SystemAdmin",
                            UsuarioModificacion = "SystemAdmin"
                        },
                        new
                        {
                            Id = new Guid("2c3d4e5f-6a7b-8c9d-0e1f-2a3b4c5d6e7f"),
                            Descripcion = "Kit de 2x16GB optimizado para alto rendimiento en servidores y compilación",
                            Estado = true,
                            FechaCreacion = new DateTime(2026, 6, 2, 3, 35, 12, 858, DateTimeKind.Utc).AddTicks(3161),
                            FechaModificacion = new DateTime(2026, 6, 2, 3, 35, 12, 858, DateTimeKind.Utc).AddTicks(3162),
                            Nombre = "Memoria RAM DDR5 32GB",
                            Precio = 125.50m,
                            UsuarioCreacion = "SystemAdmin",
                            UsuarioModificacion = "SystemAdmin"
                        },
                        new
                        {
                            Id = new Guid("3d4e5f6a-7b8c-9d0e-1f2a-3b4c5d6e7f8a"),
                            Descripcion = "Cargador ultracompacto de pared con múltiples salidas USB-C de carga rápida",
                            Estado = true,
                            FechaCreacion = new DateTime(2026, 6, 2, 3, 35, 12, 858, DateTimeKind.Utc).AddTicks(3166),
                            FechaModificacion = new DateTime(2026, 6, 2, 3, 35, 12, 858, DateTimeKind.Utc).AddTicks(3166),
                            Nombre = "Cargador GaN 65W",
                            Precio = 29.99m,
                            UsuarioCreacion = "SystemAdmin",
                            UsuarioModificacion = "SystemAdmin"
                        },
                        new
                        {
                            Id = new Guid("4e5f6a7b-8c9d-0e1f-2a3b-4c5d6e7f8a9b"),
                            Descripcion = "Resolución Ultra HD con corrección automática de luz y micrófonos duales",
                            Estado = true,
                            FechaCreacion = new DateTime(2026, 6, 2, 3, 35, 12, 858, DateTimeKind.Utc).AddTicks(3169),
                            FechaModificacion = new DateTime(2026, 6, 2, 3, 35, 12, 858, DateTimeKind.Utc).AddTicks(3170),
                            Nombre = "Cámara Web 4K Pro",
                            Precio = 95.00m,
                            UsuarioCreacion = "SystemAdmin",
                            UsuarioModificacion = "SystemAdmin"
                        },
                        new
                        {
                            Id = new Guid("5f6a7b8c-9d0e-1f2a-3b4c-5d6e7f8a9b0c"),
                            Descripcion = "Estructura ajustable con motor silencioso y panel de memoria de altura",
                            Estado = true,
                            FechaCreacion = new DateTime(2026, 6, 2, 3, 35, 12, 858, DateTimeKind.Utc).AddTicks(3174),
                            FechaModificacion = new DateTime(2026, 6, 2, 3, 35, 12, 858, DateTimeKind.Utc).AddTicks(3175),
                            Nombre = "Escritorio Elevable Eléctrico",
                            Precio = 340.00m,
                            UsuarioCreacion = "SystemAdmin",
                            UsuarioModificacion = "SystemAdmin"
                        },
                        new
                        {
                            Id = new Guid("6a7b8c9d-0e1f-2a3b-4c5d-6e7f8a9b0c1d"),
                            Descripcion = "Switch administrable metálico para montaje en rack o pared",
                            Estado = true,
                            FechaCreacion = new DateTime(2026, 6, 2, 3, 35, 12, 858, DateTimeKind.Utc).AddTicks(3179),
                            FechaModificacion = new DateTime(2026, 6, 2, 3, 35, 12, 858, DateTimeKind.Utc).AddTicks(3179),
                            Nombre = "Switch de Red 8 Puertos Gigabit",
                            Precio = 48.00m,
                            UsuarioCreacion = "SystemAdmin",
                            UsuarioModificacion = "SystemAdmin"
                        },
                        new
                        {
                            Id = new Guid("7b8c9d0e-1f2a-3b4c-5d6e-7f8a9b0c1d2e"),
                            Descripcion = "Alta cobertura y velocidad de transferencia optimizada para entornos IoT",
                            Estado = true,
                            FechaCreacion = new DateTime(2026, 6, 2, 3, 35, 12, 858, DateTimeKind.Utc).AddTicks(3183),
                            FechaModificacion = new DateTime(2026, 6, 2, 3, 35, 12, 858, DateTimeKind.Utc).AddTicks(3183),
                            Nombre = "Router WiFi 6 de Triple Banda",
                            Precio = 155.00m,
                            UsuarioCreacion = "SystemAdmin",
                            UsuarioModificacion = "SystemAdmin"
                        },
                        new
                        {
                            Id = new Guid("8c9d0e1f-2a3b-4c5d-6e7f-8a9b0c1d2e3f"),
                            Descripcion = "Patrón cardioide con filtro antipop, óptimo para videollamadas y streaming",
                            Estado = true,
                            FechaCreacion = new DateTime(2026, 6, 2, 3, 35, 12, 858, DateTimeKind.Utc).AddTicks(3190),
                            FechaModificacion = new DateTime(2026, 6, 2, 3, 35, 12, 858, DateTimeKind.Utc).AddTicks(3191),
                            Nombre = "Micrófono Condensador USB",
                            Precio = 68.50m,
                            UsuarioCreacion = "SystemAdmin",
                            UsuarioModificacion = "SystemAdmin"
                        },
                        new
                        {
                            Id = new Guid("9d0e1f2a-3b4c-5d6e-7f8a-9b0c1d2e3f4a"),
                            Descripcion = "Gabinete de pared para equipos de telecomunicación con puerta de vidrio templado",
                            Estado = true,
                            FechaCreacion = new DateTime(2026, 6, 2, 3, 35, 12, 858, DateTimeKind.Utc).AddTicks(3194),
                            FechaModificacion = new DateTime(2026, 6, 2, 3, 35, 12, 858, DateTimeKind.Utc).AddTicks(3195),
                            Nombre = "Gabinete Porta Servidor Rack 6U",
                            Precio = 110.00m,
                            UsuarioCreacion = "SystemAdmin",
                            UsuarioModificacion = "SystemAdmin"
                        },
                        new
                        {
                            Id = new Guid("0e1f2a3b-4c5d-6e7f-8a9b-0c1d2e3f4a5b"),
                            Descripcion = "Bobina de cable de par trenzado de cobre puro de alto rendimiento",
                            Estado = true,
                            FechaCreacion = new DateTime(2026, 6, 2, 3, 35, 12, 858, DateTimeKind.Utc).AddTicks(3199),
                            FechaModificacion = new DateTime(2026, 6, 2, 3, 35, 12, 858, DateTimeKind.Utc).AddTicks(3199),
                            Nombre = "Cable de Red Cat6 UTP 305m",
                            Precio = 85.00m,
                            UsuarioCreacion = "SystemAdmin",
                            UsuarioModificacion = "SystemAdmin"
                        },
                        new
                        {
                            Id = new Guid("1f2a3b4c-5d6e-7f8a-9b0c-1d2e3f4a5b6c"),
                            Descripcion = "Regulador de voltaje integrado con batería de respaldo para servidores locales",
                            Estado = true,
                            FechaCreacion = new DateTime(2026, 6, 2, 3, 35, 12, 858, DateTimeKind.Utc).AddTicks(3203),
                            FechaModificacion = new DateTime(2026, 6, 2, 3, 35, 12, 858, DateTimeKind.Utc).AddTicks(3203),
                            Nombre = "UPS Sistema de Respaldo 1500VA",
                            Precio = 195.00m,
                            UsuarioCreacion = "SystemAdmin",
                            UsuarioModificacion = "SystemAdmin"
                        },
                        new
                        {
                            Id = new Guid("2a3b4c5d-6e7f-8a9b-0c1d-2e3f4a5b6c7d"),
                            Descripcion = "Barra de luz para monitor con control de temperatura de color y brillo continuo",
                            Estado = true,
                            FechaCreacion = new DateTime(2026, 6, 2, 3, 35, 12, 858, DateTimeKind.Utc).AddTicks(3207),
                            FechaModificacion = new DateTime(2026, 6, 2, 3, 35, 12, 858, DateTimeKind.Utc).AddTicks(3207),
                            Nombre = "Lámpara de Escritorio Inteligente",
                            Precio = 38.00m,
                            UsuarioCreacion = "SystemAdmin",
                            UsuarioModificacion = "SystemAdmin"
                        },
                        new
                        {
                            Id = new Guid("3a3b4c5d-6e7f-8a9b-0c1d-2e3f4a5b6c7e"),
                            Descripcion = "Access point robusto con protección IP65 e ideal para cobertura extendida",
                            Estado = true,
                            FechaCreacion = new DateTime(2026, 6, 2, 3, 35, 12, 858, DateTimeKind.Utc).AddTicks(3211),
                            FechaModificacion = new DateTime(2026, 6, 2, 3, 35, 12, 858, DateTimeKind.Utc).AddTicks(3212),
                            Nombre = "Punto de Acceso PoE Exterior",
                            Precio = 115.00m,
                            UsuarioCreacion = "SystemAdmin",
                            UsuarioModificacion = "SystemAdmin"
                        });
                });

            modelBuilder.Entity("RedLab.API.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
