// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RedLab.API.Data;

#nullable disable

namespace RedLab.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260602020021_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RedLab.API.Entities.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"),
                            Descripcion = "Laptop de alta gama para desarrollo de software",
                            Estado = true,
                            FechaCreacion = new DateTime(2026, 6, 2, 2, 0, 20, 904, DateTimeKind.Utc).AddTicks(5589),
                            FechaModificacion = new DateTime(2026, 6, 2, 2, 0, 20, 904, DateTimeKind.Utc).AddTicks(5590),
                            Nombre = "Laptop Pro 15 pulgadas",
                            Precio = 1299.99m,
                            UsuarioCreacion = "SystemAdmin",
                            UsuarioModificacion = "SystemAdmin"
                        },
                        new
                        {
                            Id = new Guid("f4e3d2c1-b0a9-8f7e-6d5c-4b3a2a1f0e9d"),
                            Descripcion = "Monitor curvo ideal para multitasking",
                            Estado = true,
                            FechaCreacion = new DateTime(2026, 6, 2, 2, 0, 20, 904, DateTimeKind.Utc).AddTicks(5605),
                            FechaModificacion = new DateTime(2026, 6, 2, 2, 0, 20, 904, DateTimeKind.Utc).AddTicks(5606),
                            Nombre = "Monitor UltraWide 34\"",
                            Precio = 450.50m,
                            UsuarioCreacion = "SystemAdmin",
                            UsuarioModificacion = "SystemAdmin"
                        });
                });

            modelBuilder.Entity("RedLab.API.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
